name: azure_ad_oauth_mrt
description: A Flutter OAuth package for performing user authentication against
  Azure Active Directory OAuth2 v2.0 endpoint.
version: 2.0.0
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^11.2.0
  webview_flutter: ^4.14.1
  http: ^1.6.0
  shared_preferences: ^2.5.5
  dartz: ^0.10.1
  equatable: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/msalv2.js
